# Generated by Django 4.2.4 on 2023-08-18 04:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('tracking_no', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=100)),
                ('Service_Type', models.CharField(choices=[('Gas Leak', 'Gas Leak'), ('New Connection', 'New Connection'), ('Replace', 'Replace')], max_length=50)),
                ('request_detials', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TrackStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('tracking_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='app1.servicerequest')),
            ],
        ),
    ]
