# Generated by Django 4.2.4 on 2023-08-17 11:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tracking_no',
            field=models.UUIDField(default=1, unique=True, verbose_name=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrackStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.servicerequest', unique=True)),
            ],
        ),
    ]
