# Generated by Django 4.2.4 on 2023-08-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_servicerequest_tracking_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackstatus',
            name='tracking_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.servicerequest'),
        ),
    ]
