# Generated by Django 4.2.4 on 2023-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_trackstatus_tracking_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
