# Generated by Django 4.2.4 on 2023-08-17 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_customer_name_servicerequest_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='tracking_no',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
