# Generated by Django 4.2.4 on 2023-08-17 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_servicerequest_tracking_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trackstatus',
            name='tracking_no',
        ),
        migrations.AddField(
            model_name='trackstatus',
            name='service_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='app1.servicerequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackstatus',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='tracking_no',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
