# Generated by Django 4.2.4 on 2023-08-17 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_servicerequest_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='request_detials',
            new_name='request_details',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='app1.customer'),
        ),
    ]
