# Generated by Django 4.2.4 on 2023-08-17 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_servicerequest_tracking_no_trackstatus_tracking_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='id',
        ),
        migrations.AddField(
            model_name='trackstatus',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='tracking_no',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
