# Generated by Django 4.2.4 on 2023-08-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_servicerequest_id_trackstatus_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackstatus',
            name='account',
        ),
    ]
