# Generated by Django 4.2.4 on 2023-08-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_servicerequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackstatus',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.customer'),
            preserve_default=False,
        ),
    ]
