# Generated by Django 4.2.4 on 2023-08-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_request_detials_servicerequest_request_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer'),
        ),
    ]
