# Generated by Django 4.2.4 on 2023-08-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_servicerequest_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='account',
            new_name='Name',
        ),
    ]
