# Generated by Django 4.2.4 on 2023-08-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_account_servicerequest_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='Name',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.IntegerField(),
        ),
    ]
