# Generated by Django 4.2.4 on 2023-08-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_trackstatus_account'),
        ('app1', '0010_remove_trackstatus_account'),
    ]

    operations = [
    ]
