# Generated by Django 4.2.4 on 2023-08-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_customer_account_number_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='request_details',
            new_name='request_detials',
        ),
        migrations.RemoveField(
            model_name='trackstatus',
            name='service_request',
        ),
        migrations.RemoveField(
            model_name='trackstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackstatus',
            name='tracking_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.servicerequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer'),
        ),
    ]
