# Generated by Django 4.2.4 on 2023-08-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_rename_request_details_servicerequest_request_detials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='account',
        ),
    ]
