# Generated by Django 4.2.4 on 2023-08-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_merge_20230817_1709'),
        ('app1', '0014_remove_servicerequest_account'),
    ]

    operations = [
    ]
